package com.ocean.springclouid.oceanrabbitmqconsumer.mapper;

import com.ocean.springclouid.oceanrabbitmqconsumer.entity.RpTransactionMessage;

public interface RpTransactionMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rp_transaction_message
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rp_transaction_message
     *
     * @mbg.generated
     */
    int insert(RpTransactionMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rp_transaction_message
     *
     * @mbg.generated
     */
    int insertSelective(RpTransactionMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rp_transaction_message
     *
     * @mbg.generated
     */
    RpTransactionMessage selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rp_transaction_message
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RpTransactionMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rp_transaction_message
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(RpTransactionMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rp_transaction_message
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RpTransactionMessage record);
}