spring:
  rabbitmq:
    host: 192.168.3.7
    port: 5672
    username: jkstack
    password: 123qweASD
    virtual-host: /
    listener:
      simple:
        #       采用手动应答
        acknowledge-mode: manual
        #       当前监听容器数
        concurrency: 1
        #       最大数
        max-concurrency: 1
        retry:
          enabled: true
          max-attempts: 1
        publisher-confirms: true
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
  # redis配置
  redis:
    host: 192.168.3.114
    port: 7005

eureka:
  client:
    service-url:
      defaultZone: http://192.168.3.114:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    prefer-ip-address: true
