spring:
  rabbitmq:
    host: 39.108.9.37
    port: 5672
    username: dachao
    password: 123456
    virtual-host: /
    listener:
      simple:
        #       采用手动应答
        acknowledge-mode: manual
        #       当前监听容器数
        concurrency: 1
        #       最大数
        max-concurrency: 1
        retry:
          enabled: true
          max-attempts: 1
        publisher-confirms: true
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
  # redis配置
  redis:
    host: 39.108.9.37
    port: 7005
