spring:
  mail:
    host: smtp.gmail.com
    username: akenisocean164214878@gmail.com
    password: jichao164214878
    default-encoding: UTF-8
    port: 465
    test-connection: true
logging:
  level:
    root: info
