server:
  port: 23333
spring:
  application:
    name: ocean-elasticsearch
  elasticsearch:
    rest:
      uris: http://192.168.3.235:9200
      connection-timeout: 3s
  data:
    elasticsearch:
      repositories:
        enabled: true

logging:
  level:
    org.elasticsearch: trace
    org.apache.http: debug