server:
  port: 9100
spring:
  application:
    name: ocean-hystrix-provider
  http:
    encoding:
      charset: UTF-8
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    metadata-map:
      my-metadata: nishabi
      ocean-dachao: 你才是傻逼

