server:
  port: 9100
spring:
  application:
    name: ocean-hystrix-provider
  http:
    encoding:
      charset: UTF-8
eureka:
  client:
    service-url:
       defaultZone: http://39.108.9.37:8761/eureka/

