server:
  port: 11000
spring:
  application:
    name: ocean-rabbitmq-consumer
  rabbitmq:
    host: 192.168.1.240
    port: 5672
    username: guest
    password: guest
    virtual-host: /


  datasource:
    druid:
      ctrlcontract:
        url: jdbc:mysql://192.168.1.118:3306/ctrlcontract?characterEncoding=UTF-8
        username: ctrlcontract
        password: glanway2017
        initial-size: 1
        max-active: 20
        max-wait: 60000
        min-idle: 1
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: "SELECT 'x'"
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        filters: stat
      authcenter:
        url: jdbc:mysql://192.168.1.118:3306/authcenter?characterEncoding=UTF-8
        username: authcenter
        password: glanway2017
        initial-size: 1
        max-active: 20
        max-wait: 60000
        min-idle: 1
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: "SELECT 'x'"
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        filters: stat
      ctrlcommon:
        url: jdbc:mysql://192.168.1.118:3306/ctrlcommon?characterEncoding=UTF-8
        username: ctrlcommon
        password: glanway2017
        initial-size: 1
        max-active: 20
        max-wait: 60000
        min-idle: 1
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: "SELECT 'x'"
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        filters: stat
      ctrloperation:
        url: jdbc:mysql://192.168.1.118:3306/ctrloperation?characterEncoding=UTF-8
        username: ctrloperation
        password: glanway2017
        initial-size: 1
        max-active: 20
        max-wait: 60000
        min-idle: 1
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: "SELECT 'x'"
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        filters: stat
      ctrlproject:
        url: jdbc:mysql://192.168.1.118:3306/ctrlproject?characterEncoding=UTF-8
        username: ctrlproject
        password: glanway2017
        initial-size: 1
        max-active: 20
        max-wait: 60000
        min-idle: 1
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: "SELECT 'x'"
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        filters: stat
      ctrlcrm:
        url: jdbc:mysql://192.168.1.118:3306/ctrlcrm?characterEncoding=UTF-8
        username: ctrlcrm
        password: glanway2017
        initial-size: 1
        max-active: 20
        max-wait: 60000
        min-idle: 1
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        validation-query: "SELECT 'x'"
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        filters: stat