server:
  port: 9300
spring:
  application:
    name: ocean-feign-provider
  security:
    user:
      name: ocean
      password: ocean
eureka:
  client:
    service-url:
      defaultZone: http://39.108.9.37:8761/eureka/

