server:
  port: 11334
spring:
  application:
    name: ocean-demo
#  profiles:
#    active: dev


app:
  id: haha

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logging:
  level:
    org.springframework.boot.actuate: debug
