server:
  port: 11334
spring:
  application:
    name: ocean-demo
#  profiles:
#    active: dev


app:
  id: SampleApp
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
logging:
  level:
    org.springframework.boot.actuate: debug

#elasticjob:
#  zookeeper:
#    serverlists: 127.0.0.1:2181
#    namespace: boot-job