# 设置对外开放端口
server:
  port: 10000
  servlet:
    context-path: /ocean-admin
spring:
  application:
    name: ocean-admin
  # 设置用户名和密码
  security:
    user:
      name: ocean
      password: 123qweASD
#  cloud:
#    nacos:
#      # 注册中心配置
#      discovery:
#        # 注册中心地址
#        server-addr: 192.168.3.239:8848
#        # 命名空间，用来区分环境
#        namespace: di-deploy-dev
#      username: jkstack
#      password: 123qweASD

management:
  endpoints:
    web:
      exposure:
        include: '*'
    jmx:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

