server:
  port: 11000
spring:
  application:
    name: ocean-rabbitmq-consumer
  rabbitmq:
    host: 114.67.224.231
    port: 5672
    username: guest
    password: guest
    virtual-host: /
#    消息回执
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
  #    数据库和数据库线程池配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.108.9.37:3306/test?characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true
    username: root
    password: jc164214878
    hikari:
      connection-test-query: SELECT 1 FROM DUAL

mybatis:
  configuration:
#   是否支持驼峰
    map-underscore-to-camel-case: true
  type-aliases-package: com.ocean.springclouid.oceanrabbitmqconsumer.entity
#  增加自定义的handler方法
#  type-handlers-package:
  mapper-locations: classpath:mapper/*.xml
