server:
  port: 8889
spring:
  application:
    name: ocean-config-server
  cloud:
    config:
      server:
#        git:
#          uri: file:///C:/Users/Administrator/Desktop/xinqiuboche-config-yml/
#          username: jc164214878@163.com
#          password: jichao164214878
#          search-paths: /
#          clone-on-start: true
#          basedir: C:\\Users\\Administrator\\Desktop\\laji\\
        native:
          fail-on-error: true
          search-locations: file:///C:\\Users\\Administrator\\Desktop\\xinqiuboche-config-yml\\
  profiles:
    active: native


